name: Auto Merge 

on:
  schedule:
    - cron: '0 16 * * *'     # 每天北京時間 0:00
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 迁出代码
        uses: actions/checkout@v4
      
      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run script
        run: python merge.py

      - name: 推送到 output 分支
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: output
          force_orphan: true
          enable_jekyll: false
